---
slug: clockwork-girl
filename: clockwork-girl
title: A Clockwork Heart
subtitle: Change me
description: Change me.
author: Chad E Henderson
copyright: 2014
uuid: 453e7d9f-c78f-4322-a529-8da2c2a5f85b
